name: subscription-tracking

services:
  database:
    image: postgres:17.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER=postgres
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgres_password

  web:
    image: subscription-tracking-webapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=pass
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - database

networks:
  backend:
    driver: bridge

volumes:
  db-data:

secrets:
  postgres_password:
    file: secrets.txt
